### ISSUE TITLE
Error when loading Weapons

### ISSUE THREAD

**Issue by marvinside** [ChiriVulpes/deepsight.gg#34]
https://github.com/ChiriVulpes/deepsight.gg/blob/b5736c0632153f82e5606efd8fdab1f665873a30/src/model/models/items/Deepsight.ts#L116

```
Model '' failed to load: TypeError: Cannot read properties of undefined (reading 'flatMap')
    at index.js:5659:76
    at Array.flatMap (<anonymous>)
    at findObjective (index.js:5659:45)
    at async resolveShaped (index.js:5610:24)
    at async Object.apply (index.js:5594:69)
    at async Promise.all (index 2)
    at async Item.resolve (index.js:6388:13)
    at async refreshItem (index.js:7265:28)
    at async Inventory.refresh (index.js:7340:17)
(anonymous) @ index.js:2269
```

I'd suggest to replace `socket?.plugs.flatMap(...)` with `socket?.plugs`?.flatMap` as it appears that plugs might be undefined.

It seems to be causedby the "Syncopation-53", this is one of the weapons in my Inventory.

URL: https://deepsight.gg/Marvinside.7965/weapons
Weapon in light.gg: https://www.light.gg/db/items/2856514843/syncopation-53/?p=3661387068,1431678320,588594999,124408337

**Comment by ChiriVulpes** [comment]
Whoops! I'll take a look, thank you

**Comment by ChiriVulpes** [comment]
Should be fixed now!
